### ISSUE TITLE
black screen after using nnswitch in the same Xsession

### ISSUE THREAD

**Issue by mustafapc19** [Superdanby/Grub-Nvidia-Entry#13]
I am using fedora29 with negativo nvidia drivers. Using the boot parameters which is provided by your project. When I use nnswitch for the first time it changes from nvidia to the non-nvidia driver flawlessly but when I want to revert back to nvidia there's a black screen. 
video card- Nvidia gtx1060 max-q

**Comment by mustafapc19** [comment]
Yep I fixed by removing the code related to nouveau, I still dont know what the problem was, I guess it was getting into a infinite loop maybe,I dont know. Thank you guys for this awesome hack.

**Comment by Superdanby** [comment]
Hmm... I can't reproduce the problem on my machine. I'm using XPS 15 9550 with Nvidia 960m. You can check what happened during the switching process with `journalctl` from another tty. For verbose output, add `set -x` after the first line of `nnswitch.sh`.

But I'm guessing that your issue is caused by the MAX-Q series being barely supported by Nouveau.
Congratz that you solved the issue though. :+1: 

And thanks for all the people who supported this project. :smiley:

**Comment by mustafapc19** [comment]
Yeah if I start the script again from a tty its working and sometimes it just loops around in the gdm.If I just open the laptop and use nnswitch.sh twice it works perfectly but after using a little while if I use it again whole thing goes black screen, sometimes cant even switch to tty, I have switched back to ubuntu. Was kinda digging fedora.

**Comment by Superdanby** [comment]
Alright then, I'll try to figure out what went wrong in the future. And good luck with Ubuntu.
